dist: xenial
language: node_js
sudo: false

node_js:
  - "10"
  - "11.15"
  - "latest"

branches:
  only:
    - master
    - /next\/.*/

script:
  - npm run build
  - npm test

env:
  global:
    - APP_MOUNT_URI="/"
    - API_URI="/graphql/"
