dist: xenial
language: node_js
sudo: false

node_js:
  - "11.15"

branches:
  only:
    - master
    - /next\/.*/

script:
  - npm run build
  - npm test -- --ci --coverage

env:
  global:
    - APP_MOUNT_URI="/"
    - API_URI="/graphql/"

after_success:
  - codecov
